### PR TITLE
Fix typespec

### PR DESCRIPTION
**Pull request by avillen**
Hi @secretworry :wave: 

I have some dialyzer errors using this library because of some typespec issues. This MR aims to fix them. As I apply `mix format` every time I save on my editor, I have also apply `mix format` to all the library, but let me know if you don't like it or if I have done something awful fixing the specs :smile:

- `mix format`: https://github.com/secretworry/as_nested_set/commit/47c703b693e28fcd4a717fb816f0b607b53214c2
- specs: https://github.com/secretworry/as_nested_set/commit/db3f7989743f2f1fd7c9db65d1eb14dc4ca84e44

### CODE REVIEW

**Comment by secretworry** [comment]
Woo, big thx~ Definitely awesome~ I'll try to release a new version ASAP.

**Comment by avillen** [comment]
Thanks to you :) awesome library!

**Comment by avillen** [comment]
Hi @secretworry! Would it be possible to merge and release this? this way I can use the hex version instead of my fork :pray:

Thanks in advance! :smile:

**Comment by secretworry** [comment]
@avillen I have some concerns with adding parentheses to all the declarations, could you solve it or give more explanation before we can further merge the code?

**Comment by avillen** [comment]
It is the default changes that `mix format` applies and I'm not sure if this is modifiable. Anyway, if the changes in the specs https://github.com/secretworry/as_nested_set/commit/db3f7989743f2f1fd7c9db65d1eb14dc4ca84e44 looks good to you, I'll be happy to remove the `format` commit 😄

**Comment by secretworry** [comment]
@avillen Removing the format commit would be good. I will try to figure out a proper format configuration for this project later:)

**Comment by avillen** [comment]
It's been a long time, sorry. Tell me if it's okay with you now :smile:

**Pull request merged**
