### PR TITLE
Upgrade Ecto 3.0

### PR DESCRIPTION
**Pull request by nicholasjhenry**
I'll update this once the final release is available.

### CODE REVIEW

**Comment by secretworry** [comment]
@nicholasjhenry Cool~
I just created a new branch `ecto-3.0` to manage the changes required to adapt the Ecto 3.0.

**Comment by nicholasjhenry** [comment]
@secretworry What could I do to help to get this merged into master and released?

**Comment by secretworry** [comment]
@nicholasjhenry Nothing. Today, I'll switch the support for the`ecto-2.0` to a separate branch, and release a new version

**Comment by secretworry** [comment]
@nicholasjhenry Just released 3.2.0 which support the latest ecto 3.0.7 by default. Hope that helps :)

**Comment by nicholasjhenry** [comment]
That's great, thank you so much, @secretworry.

**Pull request merged**
